imports:
    - { resource: tables.yml }

services:
    forumhulp.searchresults.listener:
        class: forumhulp\searchresults\event\listener
        arguments:
            - @config
            - @controller.helper
            - @user
            - @request
            - @dbal.conn
            - @log
            - %core.root_path%
            - %core.php_ext%
            - %tables.searchresults%
        tags:
            - { name: event.listener }